### PR TITLE
Connect mesher to solver

### PR DESCRIPTION
**Pull request by int-ptr-ptr**
This PR will add a [LinearSimplexMesh2D](https://github.com/fastfem/fastfem/blob/mesh_element/fastfem/elements/linear_simplex_mesh2d.py) element type that takes a mesh as an argument and handle assembly on the mesh. The integration functions create a stack of [LinearSimplex2D](https://github.com/fastfem/fastfem/blob/mesh_element/fastfem/elements/linear_simplex2d.py#L8) fields, and delegates to LinearSimplex2D for integration on reference elements.

### CODE REVIEW

**Comment by sinaatalay** [comment]
We can merge this whenever you think it's ready @int-ptr-ptr.

**Comment by int-ptr-ptr** [comment]
I'm really sorry for taking so long to get this done. I think this marks the completion of my end of the code in terms of the final -- I will be working on the report from here.

This should all be functioning correctly. See the [new example](https://github.com/fastfem/fastfem/blob/mesh_element/examples/demo_spectral_wave.py).

Unfortunately, JAX is not an easy drop-in, so that will have to be a post-final thing, but the machinery should make it easy to add support.

**Comment by int-ptr-ptr** [comment]
> We can merge this whenever you think it's ready @int-ptr-ptr.

Before we merge, should I try to get coverage up to 95%?

**Comment by sinaatalay** [comment]
No problem at all. I'm totally fine with skipping JAX. Also, I don't mind having coverage below 95%. We can momentarily take the error threshold to 85% for the sake of the final.

**Comment by int-ptr-ptr** [comment]
I'm opening up this PR for review, mostly to request you make sure the example looks good / workable.

**Review by sinaatalay — APPROVED** [review]
The example looks very clean and works for me. The solution was quite interesting. Thank you.

**Pull request merged**
